name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  setup-release:
    name: Setup release
    runs-on: ubuntu-latest
    steps:
    - name: Create release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Get url to upload to release from output
      env:
        url: ${{ steps.create_release.outputs.upload_url }}
      run: |
        mkdir artifact
        echo $url > artifact/url.txt
        echo $(realpath artifact/url.txt)
    - name: Upload artifact to share url with other jobs
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: artifact/url.txt

  build:
    needs: setup-release
    strategy:
      matrix:
        archtecture: [ "amd64", "arm64" ]
        include:
        - archtecture: amd64
          goos: linux
          arch: amd64
        - archtecture: arm64
          goos: linux
          arch: arm64


    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'
        cache-dependency-path: ./go.sum
        cache: true

    - run: go mod download

    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 21

    - name: install pnpm
      run: npm install -g pnpm

    - name: install pnpm dependencies
      run: pnpm install --prefix ./front

    - name: build frontend
      run: pnpm run --dir ./front build

    - name: Build for ${{ matrix.arch }}
      run: GCO_ENABLED=0 GOOS=$goos GOARCH=${{ matrix.arch }} go build -ldflags="-s -w" -trimpath

    - name: Archive
      run: |
        zip -r ${{ github.event.repository.name }}-${{ matrix.goos }}-${{ matrix.arch }}-${{ github.ref_name }}.zip \
          ./wol \
          ./.env.example \
          ./config.schema.json \
          ./config.json.example \
          ./setup-service.sh \
          ./public

    - name: Download artifact to get url to upload to release
      uses: actions/download-artifact@v4
      with:
        name: my-artifact

    - name: Get url to upload to release from artifact
      id: get_url
      run: |
        url=$(cat artifact/url.txt)
        echo "##[set-output name=upload_url;]$url"

    - name: Upload release asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_url.outputs.upload_url }}
        asset_path: ./${{ github.event.repository.name }}-${{ matrix.goos }}-${{ matrix.arch }}-${{ github.ref_name }}.zip
        asset_name: ${{ github.event.repository.name }}-${{ matrix.goos }}-${{ matrix.arch }}-${{ github.ref_name }}.zip
        asset_content_type: application/zip
